name: '🚀 publish'


on:
  push:
    branches:
      - main

jobs:
  release:
    name: 🚀 publish
    if: "contains(github.event.head_commit.message, 'deploy')"
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v2.3.3
      - name: 🟢 node
        uses: actions/setup-node@v1.4.4
        with:
            node-version: 12
            registry-url: https://registry.npmjs.org
      - name: 🚀 publish
        run: npm publish --access public
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
